spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/leadme
#    username: sa
#    password:
    url: jdbc:mysql://springboot-db.c5wjpykozkbv.ap-northeast-2.rds.amazonaws.com:3306/leadme
    username:
    password:
    driver-class-name: org.h2.Driver
  profiles:
    active: local

#  mvc:
#    hiddenmethod:
#      filter: enabled=true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace
